import Head from 'next/head'
import { Button } from 'antd'
import Header from '../components/Header/Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>zengjichaoren's blog</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
      </Head>
      <Header/>
    </div>
  )
}
